#!/usr/bin/env python3
from argparse import ArgumentParser, ArgumentTypeError, FileType
from src.dig import get_mx_servers
from src.smtp import verify_email


if __name__ == "__main__":
    # TODO:
    # handle stdin input
    parser = ArgumentParser(description="Email tools.")

    subparser = parser.add_subparsers(help="commands", dest="command", required=True)

    verify_parser = subparser.add_parser(
        "verify", help="Verify an email (not always possible)"
    )
    # verify_parser.add_argument(
    # "-i", metavar="input_file", help="Input txt list with emails to check.", type=FileType("r"))
    verify_parser.add_argument("email", help="Email you would like to check.", type=str)

    mx_parser = subparser.add_parser("mx", help="Get MX records for a domain or email")
    mx_parser.add_argument("domain", metavar="domain|email", type=str)

    args = parser.parse_args()
    if args.command == "verify":
        verification = verify_email(args.email, get_mx_servers)
        print("Verification:", verification)
    elif args.command == "mx":
        domain = args.domain
        if "@" in domain:
            _, domain = domain.split("@")
        elif "." not in domain:
            raise ValueError("A valid domain|email is required.")
        mxs = get_mx_servers(domain)
        print("MX hosts:", mxs)
